import {chromium} from '../rover/node_modules/playwright-core/index.mjs';import {startFieldServer} from '../field-lab/server.mjs';import {loadRapier} from '../../experiments/rover3d/engine.mjs';import {createRouteSession} from '../../packages/routes/runtime.mjs';import {defaultRoute} from '../../packages/routes/contract.mjs';import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';
const server=await startFieldServer(0),R=await loadRapier(),browser=await chromium.launch({executablePath:process.env.CHROME_PATH??'/usr/bin/google-chrome',headless:true,chromiumSandbox:true});const context=await browser.newContext({acceptDownloads:true}),page=await context.newPage(),passed=[],errors=[],external=[];page.setDefaultTimeout(15000);
page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',r=>r.request().url().startsWith(server.url)?r.continue():(external.push(r.request().url()),r.abort()));await mkdir('evidence/routes-local',{recursive:true});
const idle=()=>page.waitForFunction(()=>document.body.dataset.busy==='false');
try{await page.goto(server.url+'#digital');await page.waitForFunction(()=>document.body.dataset.ready==='true');await page.locator('[data-package="digital.audit"]').click();
 for(const [host,id] of [['rover','rover.flow'],['drone','drone.cinema'],['humanoid','humanoid.fluid']]){
 const route=defaultRoute(host),s=createRouteSession(R,route,id);let record;try{s.advance(24);s.stop();record=s.export();}finally{s.dispose();}
 await page.locator('#inspection-file').setInputFiles({name:host+'-route.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(record))});await idle();await page.locator('#run-digital').click();await idle();
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export-results').click()]);const file='evidence/routes-local/audit-'+host+'.json';await download.saveAs(file);const result=JSON.parse(await readFile(file,'utf8'));
 assert.equal(result.valid,true);assert.equal(result.summary.steps,24);assert.equal(result.summary.scope,'custom-route');assert.deepEqual(result.summary.route,route);assert.equal(result.installation,'not-performed');passed.push('AUDIT imports and reexecutes '+host+' route recordings in the browser');
 await page.locator('#inspection-file').setInputFiles({name:'false-completion.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...record,finalStatus:'succeeded'}))});await idle();await page.locator('#run-digital').click();await idle();assert.equal(await page.locator('#error').isVisible(),true);assert.equal(await page.locator('#export-results').isDisabled(),true);passed.push(host+' route false completion is rejected without stale successful evidence');
 }
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);passed.push('Route evidence inspection makes no external request and installs no package');console.log(passed.map(s=>'PASS '+s).join(String.fromCharCode(10)));
}finally{await writeFile('evidence/routes-local/audit-browser-results.json',JSON.stringify({passed,errors,external},null,2));await browser.close();await server.close();}
