import {readRoute,parseRoute,defaultRoute,ROUTE_LIMITS,MAX_CHECKPOINTS,MAX_ROUTE_BYTES} from '/packages/routes/contract.mjs';
/** Draft data only. Applying is an explicit callback; drawing never moves a machine. */
export function createRouteEditor(element,{onApply}={}){
 let host='rover',locked=false,revision=0,selected=0,drag=null,pending=false;const states=new Map();
 const state=()=>{if(!states.has(host))states.set(host,{draft:structuredClone(defaultRoute(host)),applied:null});return states.get(host);};
 const $=id=>element.querySelector('[data-route="'+id+'"]');
 element.classList.add('route-studio');
 element.innerHTML='<details><summary><span>ROUTE STUDIO</span><strong data-route="badge">Fixed benchmark</strong><small>Set checkpoints ↗</small></summary><div class="route-content"><div class="route-top"><label>Route name<input data-route="name" maxlength="60"></label><p data-route="scope"></p></div><div class="route-grid"><div><canvas data-route="canvas" width="500" height="240" tabindex="0" aria-label="Route plan. Click to add a checkpoint or drag a numbered checkpoint. Exact coordinates are editable in the table."></canvas><p class="route-hint" data-route="hint"></p></div><div><div class="route-table-wrap"><table><caption class="sr">Ordered checkpoint coordinates</caption><thead><tr><th>Point</th><th>X</th><th>Y</th><th>Z</th><th>Order / remove</th></tr></thead><tbody data-route="rows"></tbody></table></div><button type="button" data-route="add">Add checkpoint</button></div></div><p data-route="message" role="status" aria-live="polite"></p><div class="route-actions"><button type="button" data-route="apply">Apply route & reset run</button><button type="button" data-route="fixed">Use fixed benchmark</button><button type="button" data-route="reset">Reset draft</button><button type="button" data-route="export">Export route</button><label class="route-import">Import route<input data-route="file" type="file" accept=".json,application/json"></label></div><p class="route-hint">Draft edits do not move the machine. Apply resets the run. Custom routes are exploratory tests, not certified benchmarks or learned-policy evaluation.</p></div></details>';
 const canvas=$('canvas'),ctx=canvas.getContext('2d');
 function validation(){try{return {route:readRoute(state().draft,host),error:null};}catch(e){return {route:null,error:e.message};}}
 function projection(){const l=ROUTE_LIMITS[host],width=canvas.width,height=canvas.height,pad=30;
  return {width,height,pad,l,to:p=>({x:pad+(p[l.axes[0]]-l.horizontal[0])/(l.horizontal[1]-l.horizontal[0])*(width-pad*2),y:height-pad-(p[l.axes[1]]-l.vertical[0])/(l.vertical[1]-l.vertical[0])*(height-pad*2)})};}
 function draw(){const {width,height,pad,l,to}=projection();ctx.clearRect(0,0,width,height);ctx.fillStyle='#19282d';ctx.fillRect(0,0,width,height);ctx.strokeStyle='#3d5a59';ctx.lineWidth=1;
  for(let i=0;i<=8;i++){const x=pad+(width-2*pad)*i/8,y=pad+(height-2*pad)*i/8;ctx.beginPath();ctx.moveTo(x,pad);ctx.lineTo(x,height-pad);ctx.moveTo(pad,y);ctx.lineTo(width-pad,y);ctx.stroke();}
  ctx.fillStyle='#c9d9cf';ctx.font='11px monospace';ctx.fillText(l.axes[0].toUpperCase()+' →',width-58,height-8);ctx.fillText(l.axes[1].toUpperCase()+' ↑',7,18);
  const points=state().draft.points;ctx.strokeStyle='#8cafaa';ctx.lineWidth=2;ctx.beginPath();points.forEach((p,i)=>{const q=to(p);if(!Number.isFinite(q.x+q.y))return;i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);});ctx.stroke();
  points.forEach((p,i)=>{const q=to(p);if(!Number.isFinite(q.x+q.y))return;ctx.beginPath();ctx.fillStyle=i===selected?'#edca8d':'#91b6ad';ctx.arc(q.x,q.y,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#13272c';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 11px monospace';ctx.fillText(String(i+1),q.x,q.y);});ctx.textAlign='left';ctx.textBaseline='alphabetic';
 }
 function refresh(note){const v=validation(),s=state(),changed=JSON.stringify(s.draft)!==JSON.stringify(s.applied);
  $('badge').textContent=s.applied?'Custom route · '+s.applied.points.length+' checkpoints':'Fixed benchmark';
  $('message').textContent=note??v.error??(s.applied?(changed?'Unapplied draft changes. Current run keeps the applied route.':'Applied route: '+s.applied.name):'Draft only. Apply to run these checkpoints.');
  $('message').dataset.invalid=String(!!v.error);$('apply').disabled=locked||pending||!v.route;$('export').disabled=!v.route;$('fixed').disabled=locked||pending;$('add').disabled=s.draft.points.length>=MAX_CHECKPOINTS;draw();
 }
 function render(){const s=state();$('name').value=s.draft.name;$('rows').replaceChildren();
  s.draft.points.forEach((p,i)=>{const tr=document.createElement('tr'),label=document.createElement('th');label.scope='row';label.textContent=String(i+1).padStart(2,'0');tr.append(label);
   for(const axis of ['x','y','z']){const td=document.createElement('td'),input=document.createElement('input');input.type='number';input.step='.01';input.value=p[axis];input.setAttribute('aria-label','Checkpoint '+(i+1)+' '+axis.toUpperCase());input.dataset.index=i;input.dataset.axis=axis;input.disabled=(host==='rover'&&axis==='y')||(host==='humanoid'&&axis==='x');input.oninput=()=>{s.draft.points[i][axis]=input.value===''?NaN:Number(input.value);selected=i;refresh();};td.append(input);tr.append(td);}
   const td=document.createElement('td');for(const [action,label] of [['up','↑'],['down','↓'],['remove','×']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.action=action;b.dataset.index=i;b.setAttribute('aria-label',(action==='remove'?'Remove':'Move '+action)+' checkpoint '+(i+1));b.disabled=action==='up'?i===0:action==='down'?i===s.draft.points.length-1:s.draft.points.length===1;
    b.onclick=()=>{if(action==='remove')s.draft.points.splice(i,1);else{const j=i+(action==='up'?-1:1);[s.draft.points[i],s.draft.points[j]]=[s.draft.points[j],s.draft.points[i]];}selected=Math.min(i,s.draft.points.length-1);render();};td.append(b);}tr.append(td);$('rows').append(tr);});
  $('scope').textContent=host==='drone'?'Plan X/Z ±2.5m · altitude0.6–4m':host==='rover'?'Flat lane · X ±3.5m · Z -7–9m':'Arm reach plane · X0.32m · reachable joint limits';
  $('hint').textContent=host==='drone'?'Click to add; drag a point in X/Z. Set altitude Y in the table.':'Click to add; drag numbered points. Use the coordinate fields for precision.';refresh();
 }
 function eventPoint(e){const r=canvas.getBoundingClientRect(),g=projection(),x=(e.clientX-r.left)/r.width*canvas.width,y=(e.clientY-r.top)/r.height*canvas.height;const p=host==='humanoid'?{x:.32,y:1.3,z:.4}:host==='rover'?{x:0,y:.5,z:0}:{x:0,y:state().draft.points[selected]?.y??1.8,z:0};
  p[g.l.axes[0]]=+(g.l.horizontal[0]+Math.max(0,Math.min(1,(x-g.pad)/(g.width-2*g.pad)))*(g.l.horizontal[1]-g.l.horizontal[0])).toFixed(2);
  p[g.l.axes[1]]=+(g.l.vertical[0]+Math.max(0,Math.min(1,(g.height-g.pad-y)/(g.height-2*g.pad)))*(g.l.vertical[1]-g.l.vertical[0])).toFixed(2);return {p,x,y};}
 canvas.onpointerdown=e=>{if(e.button!==0)return;const q=eventPoint(e),to=projection().to,points=state().draft.points,index=points.findIndex(p=>Math.hypot(to(p).x-q.x,to(p).y-q.y)<17);
  if(index>=0){selected=index;drag=index;canvas.setPointerCapture(e.pointerId);draw();}else if(points.length<MAX_CHECKPOINTS){points.push(q.p);selected=points.length-1;render();}};
 canvas.onpointermove=e=>{if(drag===null)return;if(!canvas.hasPointerCapture(e.pointerId)){drag=null;render();return;}const p=eventPoint(e).p;if(host==='drone')p.y=state().draft.points[drag].y;state().draft.points[drag]=p;draw();};
 canvas.onpointerup=e=>{if(drag!==null){drag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);render();}};canvas.onpointercancel=()=>{drag=null;render();};canvas.onlostpointercapture=()=>{drag=null;render();};
 $('name').oninput=()=>{state().draft.name=$('name').value;refresh();};
 $('add').onclick=()=>{const s=state(),p=structuredClone(s.draft.points.at(-1));if(host==='humanoid'){p.y=Math.max(.95,Math.min(1.85,p.y-.1));}else p.z=Math.min(host==='rover'?9:2.5,p.z+.5);s.draft.points.push(p);selected=s.draft.points.length-1;render();};
 async function apply(next){if(locked||pending)return;const s=state(),g=revision,previous=s.applied;let note;pending=true;s.applied=next;refresh();try{if(await onApply?.(next)===false)throw new Error('Application rejected');note=next?'Applied '+next.name+' · run reset.':'Fixed benchmark restored · run reset.';}catch{s.applied=previous;note='Route application failed; previous selection retained. Use Reset to recover.';}finally{if(g===revision){pending=false;refresh(note);}}}
 $('apply').onclick=()=>{const v=validation();if(v.route)return apply(v.route);};
 $('fixed').onclick=()=>apply(null);
 $('reset').onclick=()=>{state().draft=structuredClone(defaultRoute(host));selected=0;render();};
 $('export').onclick=()=>{const v=validation();if(!v.route)return;const url=URL.createObjectURL(new Blob([JSON.stringify(v.route,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='STONE-'+host+'-route.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('file').onchange=async()=>{const f=$('file').files[0],g=revision;if(!f)return;try{if(f.size>MAX_ROUTE_BYTES)throw new Error('Route JSON is limited to8KiB.');const text=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await f.arrayBuffer());if(g!==revision)return;state().draft=structuredClone(parseRoute(text,host));selected=0;render();refresh('Imported draft. Apply to start a new run.');}catch(e){if(g===revision)refresh('Import rejected: '+e.message);}finally{$('file').value='';}};
 return Object.freeze({setHost(id){if(!Object.hasOwn(ROUTE_LIMITS,id)){element.hidden=true;revision++;return null;}element.hidden=false;host=id;selected=0;drag=null;pending=false;revision++;render();return state().applied;},setLocked(value){locked=!!value;refresh();},applied:()=>state().applied});
}
