import {chromium} from '../rover/node_modules/playwright-core/index.mjs';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {startFieldServer} from './server.mjs';
import {loadRapier} from '../../experiments/rover3d/engine.mjs';
import {benchmark} from '../../packages/lab/benchmark.mjs';
import {replayHumanoidSession} from '../../packages/lab/humanoid-session.mjs';
import {replayDroneSession} from '../../packages/lab/drone-session.mjs';
const out=process.env.STONE_EVIDENCE_DIR??'evidence/field-local';await mkdir(out,{recursive:true});
const server=await startFieldServer(0),browser=await chromium.launch({executablePath:process.env.CHROME_PATH??'/usr/bin/google-chrome',headless:true,chromiumSandbox:true});
const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await context.newPage();
const errors=[],external=[],passed=[];page.on('pageerror',e=>errors.push(e.message));
await context.route('**/*',r=>{if(r.request().url().startsWith(server.url))return r.continue();external.push(r.request().url());return r.abort();});
const check=async(name,fn)=>{await fn();passed.push(name);console.log('PASS',name);};
const idle=()=>page.waitForFunction(()=>document.body.dataset.busy==='false');
const phase=()=>page.getAttribute('body','data-phase');
const tick=async()=>Number(await page.locator('#tick').textContent());
async function download(id,name){const event=page.waitForEvent('download');await page.locator(id).click();const d=await event,path=out+'/'+name;await d.saveAs(path);return JSON.parse(await readFile(path,'utf8'));}
try{
 await check('ordinary HTTP starts the real humanoid worker and WebGL renderer',async()=>{await page.goto(server.url);await page.waitForFunction(()=>document.body.dataset.ready==='true',{},{timeout:8000});assert.equal(await page.locator('#renderer-status').textContent(),'Three.js / WebGL 2');assert.equal(await tick(),0);});
 await check('arm Step and live swap preserve pose and simulation time',async()=>{await page.locator('#step').click();await idle();assert.equal(await tick(),1);const xyz=await page.locator('#coordinates').textContent();await page.locator('[data-package="humanoid.brisk"]').click();await idle();assert.equal(await tick(),1);assert.equal((await page.locator('#coordinates').textContent()).split(' / ')[0],xyz.split(' / ')[0]);});
 await check('camera Home never commands the machine',async()=>{const n=await tick();await page.locator('#home').click();await page.waitForTimeout(60);assert.equal(await tick(),n);});
 await check('live arm runs, pauses and remains stable',async()=>{await page.locator('#start').click();await page.waitForFunction(()=>Number(document.querySelector('#tick').textContent)>30);await page.locator('#pause').click();await idle();const n=await tick();await page.waitForTimeout(100);assert.equal(await tick(),n);assert.equal(await phase(),'paused');});
 await check('Stop export replays with terminal status in Node and browser',async()=>{await page.locator('#stop').click();assert.equal(await phase(),'stopped');const d=await download('#export-session','arm-session.json');assert.equal(d.finalStatus,'stopped');const r=replayHumanoidSession(await loadRapier(),JSON.stringify(d));assert.equal(r.state.frame.status,'stopped');assert.equal(r.state.frame.tick,await tick());await page.locator('#replay').click();await idle();assert.equal(await phase(),'replay');});
 await check('return from replay preserves stopped state and allows comparison',async()=>{await page.locator('#live').click();assert.equal(await phase(),'stopped');await page.locator('#compare').click();await idle();const d=await download('#export-results','arm-comparison.json');assert.deepEqual(d.results,benchmark(await loadRapier(),'humanoid','reach').results);});
 await check('reset recovers after terminated worker and completes a full arm task',async()=>{await page.locator('#reset').click();await idle();await page.locator('#start').click();await page.waitForFunction(()=>document.body.dataset.phase==='complete',{},{timeout:15000});assert.equal(await page.locator('#completed').textContent(),'3 / 3');});
 await check('drone tab starts its own actual physics and profile',async()=>{await page.locator('[data-host="drone"]').click();await idle();assert.equal(await page.locator('#passport-title').textContent(),'CINEMA');assert.equal(await tick(),0);await page.locator('#step').click();await idle();assert.equal(await tick(),1);assert.match(await page.locator('#passport').textContent(),/stone.drone.rotors/);});
 await check('host-specific labels and distinguishable module identities',async()=>{assert.match(await page.locator('#compare').textContent(),/flight/);const colors=await page.locator('.stone').evaluateAll(nodes=>nodes.map(n=>getComputedStyle(n).color));assert.equal(new Set(colors).size,3);});
 await check('drone task changes reset host; swaps retain momentum and replay',async()=>{await page.selectOption('#task','inspection');await idle();await page.locator('#start').click();await page.waitForFunction(()=>Number(document.querySelector('#tick').textContent)>25);await page.locator('#pause').click();await idle();const n=await tick();await page.locator('[data-package="drone.agile"]').click();await idle();assert.equal(await tick(),n);await page.locator('#step').click();await idle();await page.locator('#stop').click();const d=await download('#export-session','drone-session.json');assert.equal(d.assignments.at(-1),'drone.agile');const r=replayDroneSession(await loadRapier(),JSON.stringify(d));assert.equal(r.state.frame.tick,await tick());assert.equal(r.state.frame.status,'stopped');await page.locator('#replay').click();await idle();assert.equal(await phase(),'replay');await page.locator('#live').click();});
 await check('all drone benchmark results agree with Node under unchanged hardware',async()=>{await page.locator('#compare').click();await idle();const d=await download('#export-results','drone-comparison.json');assert.deepEqual(d.results,benchmark(await loadRapier(),'drone','inspection').results);});
 await check('digital BRIEF runs drone tools locally without model inference',async()=>{await page.locator('[data-host="digital"]').click();await page.locator('[data-package="digital.brief"]').click();await page.selectOption('#digital-task','drone:inspection');await page.locator('#run-digital').click();await idle();const d=await download('#export-results','digital-report.json');assert.equal(d.actualExecution,'local');assert.equal(d.model,null);assert.equal(d.results.length,3);assert.match(await page.locator('#report').textContent(),/3\/3/);});
 await check('cloud stays disabled; HYBRID requires explicit labelled local fallback',async()=>{await page.locator('[data-package="digital.analyst"]').click();assert.equal(await page.locator('#run-digital').isDisabled(),true);await page.locator('[data-package="digital.hybrid"]').click();assert.equal(await page.locator('#run-digital').isDisabled(),true);await page.locator('#local-fallback').check();await page.locator('#run-digital').click();await idle();const d=await download('#export-results','hybrid.json');assert.equal(d.actualExecution,'local-only');assert.equal(d.model,null);});
 await check('host switching drops stale work and returns a usable arm',async()=>{await page.locator('[data-host="humanoid"]').click();await idle();assert.equal(await tick(),0);assert.equal(await page.locator('#step').isEnabled(),true);});
 await check('native keyboard controls select and stop',async()=>{await page.locator('h1').click();await page.keyboard.press('2');await idle();assert.equal(await page.locator('#passport-title').textContent(),'PRECISE');await page.keyboard.press('Space');await page.waitForFunction(()=>Number(document.querySelector('#tick').textContent)>5);await page.keyboard.press('Escape');assert.equal(await phase(),'stopped');});
 await check('camera fallback and narrow layouts remain usable',async()=>{await page.locator('#viewplan').click();assert.equal(await page.locator('#plan').isVisible(),true);for(const width of [390,320]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:1440,height:1100});await page.locator('#view3d').click();});
 await check('rendered desktop and narrow evidence from actual engine states',async()=>{await page.locator('[data-host="drone"]').click();await idle();await page.locator('#start').click();await page.waitForFunction(()=>Number(document.querySelector('#tick').textContent)>90);await page.locator('#pause').click();await idle();await page.screenshot({path:out+'/drone-desktop.png',fullPage:true});await page.locator('[data-host="humanoid"]').click();await idle();await page.locator('#start').click();await page.waitForFunction(()=>Number(document.querySelector('#tick').textContent)>80);await page.locator('#pause').click();await idle();await page.screenshot({path:out+'/humanoid-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:900});await page.screenshot({path:out+'/mobile.png',fullPage:true});});
 await check('no external requests or JavaScript errors',async()=>{assert.deepEqual(external,[]);assert.deepEqual(errors,[]);});
}finally{await writeFile(out+'/results.json',JSON.stringify({browser:browser.version(),passed,errors,external},null,2));await browser.close();await server.close();}
