import {chromium} from '../rover/node_modules/playwright-core/index.mjs';
import assert from 'node:assert/strict';import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {startFieldServer} from './server.mjs';
const server=await startFieldServer(0),browser=await chromium.launch({executablePath:process.env.CHROME_PATH??'/usr/bin/google-chrome',headless:true,chromiumSandbox:true});
const out=process.env.STONE_EVIDENCE_DIR??'evidence/field-local';await mkdir(out,{recursive:true});const passed=[];
const source=await readFile(new URL('./worker.mjs',import.meta.url),'utf8');
async function check(name,fn){const context=await browser.newContext({viewport:{width:1100,height:900}}),page=await context.newPage();try{await fn(page);passed.push(name);console.log('PASS',name);}finally{await context.close();}}
async function ready(p){await p.goto(server.url);await p.waitForFunction(()=>document.body.dataset.ready==='true');}
const phase=(p,value)=>p.waitForFunction(value=>document.body.dataset.phase===value,value);
try{
 await check('genuine infinite worker stays stoppable; reset recovers',async p=>{await p.route('**/worker.mjs',r=>r.fulfill({contentType:'text/javascript',body:source.replace('const p=m.payload;let result;',"if(m.type==='advance')while(true){};const p=m.payload;let result;")}));await ready(p);await p.locator('#step').click();await p.waitForFunction(()=>document.body.dataset.busy==='true');await p.locator('#stop').click();await phase(p,'stopped');assert.equal(await p.locator('#tick').textContent(),'0');await p.unroute('**/worker.mjs');await p.locator('#reset').click();await phase(p,'ready');await p.locator('#step').click();await p.waitForFunction(()=>document.querySelector('#tick').textContent==='1');});
 await check('missing worker fails visibly, without a permanent loading state',async p=>{await p.route('**/worker.mjs',r=>r.abort());await p.goto(server.url);await phase(p,'error');assert.equal(await p.locator('#error').isVisible(),true);assert.equal(await p.locator('#reset').isEnabled(),true);});
 await check('malformed acknowledged batch cannot advance display or recording',async p=>{await p.route('**/worker.mjs',r=>r.fulfill({contentType:'text/javascript',body:source.replace('const p=m.payload;let result;',"if(m.type==='advance'){self.postMessage({id:m.id,ok:true,result:{state:{},frames:[],actions:[]}});return;}const p=m.payload;let result;")}));await ready(p);await p.locator('#step').click();await phase(p,'error');assert.equal(await p.locator('#tick').textContent(),'0');assert.match(await p.locator('#record-count').textContent(),/^0 decisions/);});
 await check('real WebGL context loss falls back while the engine can still step',async p=>{await ready(p);await p.evaluate(()=>document.querySelector('#viewport canvas').getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await p.locator('#plan').waitFor({state:'visible'});await p.locator('#step').click();await p.waitForFunction(()=>document.querySelector('#tick').textContent==='1');});
 await check('digital Cancel kills stalled computation; switching host recovers',async p=>{await p.route('**/worker.mjs',r=>r.fulfill({contentType:'text/javascript',body:source.replace('const p=m.payload;let result;',"if(m.type==='compare')while(true){};const p=m.payload;let result;")}));await ready(p);await p.locator('[data-host="digital"]').click();await p.locator('#run-digital').click();await p.waitForFunction(()=>document.body.dataset.busy==='true');await p.locator('#stop-digital').click();assert.equal(await p.getAttribute('body','data-busy'),'false');assert.match(await p.locator('#digital-state').textContent(),/Cancelled/);await p.unroute('**/worker.mjs');await p.locator('[data-host="drone"]').click();await phase(p,'ready');});
 await check('AUDIT cancellation terminates a genuinely stalled inspection worker',async p=>{await p.route('**/worker.mjs',r=>r.fulfill({contentType:'text/javascript',body:source.replace('const p=m.payload;let result;',"if(m.type==='inspect')while(true){};const p=m.payload;let result;")}));await ready(p);await p.locator('[data-host="digital"]').click();await p.locator('[data-package="digital.audit"]').click();await p.locator('#inspection-file').setInputFiles({name:'data.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":"0.2.0"}')});await p.waitForFunction(()=>document.body.dataset.busy==='false');await p.locator('#run-digital').click();await p.waitForFunction(()=>document.body.dataset.busy==='true');await p.locator('#stop-digital').click();assert.equal(await p.getAttribute('body','data-busy'),'false');assert.equal(await p.locator('#export-results').isDisabled(),true);await p.unroute('**/worker.mjs');await p.locator('[data-host="drone"]').click();await phase(p,'ready');});
 await check('worker rejects unreviewed operations and cross-host installation',async p=>{await ready(p);const values=await p.evaluate(async()=>{const w=new Worker('/worker.mjs',{type:'module'}),ask=(id,type,payload)=>new Promise(resolve=>{w.onmessage=e=>resolve(e.data);w.postMessage({id,type,payload});});try{const bad=await ask(1,'execute',{url:'https://example.invalid/code'}),start=await ask(2,'start',{host:'humanoid',task:'reach',stoneId:'humanoid.fluid'}),wrong=await ask(3,'select',{stoneId:'drone.agile'});return [bad.ok,start.ok,wrong.ok];}finally{w.terminate();}});assert.deepEqual(values,[false,true,false]);});
 await check('engine deadline handles stalled worker without user intervention',async p=>{await p.route('**/worker.mjs',r=>r.fulfill({contentType:'text/javascript',body:source.replace('const p=m.payload;let result;',"if(m.type==='advance')while(true){};const p=m.payload;let result;")}));await ready(p);await p.locator('#step').click();await phase(p,'error');assert.equal(await p.getAttribute('body','data-busy'),'false');});
}finally{await writeFile(out+'/fault-results.json',JSON.stringify({browser:browser.version(),passed},null,2));await browser.close();await server.close();}
