import {chromium} from '../rover/node_modules/playwright-core/index.mjs';
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {startFieldServer} from './server.mjs';
import {manifestFor} from '../../packages/contract/reference.mjs';
import {parseManifest} from '../../packages/contract/manifest.mjs';
import {loadRapier} from '../../experiments/rover3d/engine.mjs';
import {createDroneSession} from '../../packages/lab/drone-session.mjs';
const out='evidence/field-local/inspection';await mkdir(out,{recursive:true});
const server=await startFieldServer(0),browser=await chromium.launch({executablePath:process.env.CHROME_PATH??'/usr/bin/google-chrome',headless:true,chromiumSandbox:true});
const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await context.newPage();page.setDefaultTimeout(5000);
const errors=[],external=[],passed=[];page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',r=>{if(r.request().url().startsWith(server.url))return r.continue();external.push(r.request().url());return r.abort();});
const idle=()=>page.waitForFunction(()=>document.body.dataset.busy==='false');
const check=async(name,fn)=>{await fn();passed.push(name);console.log('PASS',name);};
const upload=async text=>{await page.locator('#inspection-file').setInputFiles({name:'STONE-data.json',mimeType:'application/json',buffer:Buffer.from(text)});await idle();};
const execute=async()=>{await page.locator('#run-digital').click();await idle();};
async function download(button,name){await page.locator(button).waitFor({state:'visible',timeout:1000});const [d]=await Promise.all([page.waitForEvent('download'),page.locator(button).click()]);const p=out+'/'+name;await d.saveAs(p);return JSON.parse(await readFile(p,'utf8'));}
try{
 await page.goto(server.url);await page.waitForFunction(()=>document.body.dataset.ready==='true');
 await check('exported core manifest uses the original standard shape and exact runtime identities',async()=>{const m=await download('#export-manifest','manifest.json');assert.equal(parseManifest(JSON.stringify(m)).valid,true);assert.equal(m.schemaVersion,'0.2.0');assert.equal(m.compatibility.profile,'stone.humanoid.reach/0.1');assert.equal(m.implementation.modelRef,null);});
 await check('AUDIT imports and inspects a manifest entirely in the local worker',async()=>{await page.locator('[data-host="digital"]').click();await page.locator('[data-package="digital.audit"]').click();const text=JSON.stringify(manifestFor('drone.cinema'));await upload(text);await execute();const r=await download('#export-results','inspection-manifest.json');assert.equal(r.kind,'manifest');assert.equal(r.valid,true);assert.equal(r.compatibility.compatible,true);assert.equal(r.source.sha256,createHash('sha256').update(text).digest('hex'));assert.equal(r.installation,'not-performed');});
 await check('cross-host compatibility failure is visible without declaring the file invalid',async()=>{await page.selectOption('#inspection-target','humanoid');await execute();const r=await download('#export-results','incompatible.json');assert.equal(r.valid,true);assert.equal(r.compatibility.compatible,false);assert.match(await page.locator('#report').textContent(),/Not compatible/);});
 await check('imported drone recording is reexecuted with its terminal state retained',async()=>{const s=createDroneSession(await loadRapier());let text;try{s.advance(24);s.stop();text=JSON.stringify(s.export(),null,2);}finally{s.dispose();}await page.selectOption('#inspection-target','auto');await upload(text);await execute();const r=await download('#export-results','inspection-recording.json');assert.equal(r.verification,'engine-reexecution');assert.equal(r.summary.steps,24);assert.equal(r.summary.status,'stopped');});
 await check('forged success is rejected and stale successful output is cleared',async()=>{const s=createDroneSession(await loadRapier());const d=structuredClone(s.export());s.dispose();d.finalStatus='succeeded';await upload(JSON.stringify(d));await execute();assert.equal(await page.locator('#error').isVisible(),true);assert.equal(await page.locator('#export-results').isDisabled(),true);});
 await check('file metadata is displayed as text, never interpreted as HTML',async()=>{const m=structuredClone(manifestFor('humanoid.fluid'));m.name='<img src="https://invalid.example/x" onerror="globalThis.attacked=true">';await upload(JSON.stringify(m));await execute();assert.equal(await page.locator('#report img').count(),0);assert.equal(await page.evaluate(()=>globalThis.attacked),undefined);});
 await check('oversized native files are rejected before inspection',async()=>{await page.locator('#inspection-file').setInputFiles({name:'too-large.json',mimeType:'application/json',buffer:Buffer.alloc(2097153,32)});await idle();assert.equal(await page.locator('#run-digital').isDisabled(),true);assert.equal(await page.locator('#error').isVisible(),true);});
 await check('malformed UTF8 is not silently converted into different evidence',async()=>{await page.locator('#inspection-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from([255])});await idle();assert.equal(await page.locator('#run-digital').isDisabled(),true);});
 await check('cloud metadata can be inspected but neither installed nor remotely invoked',async()=>{const m=structuredClone(manifestFor('digital.brief'));m.implementation={kind:'model-harness',modelRef:'example.provider@0.1.0'};m.execution={mode:'cloud',offlineBehavior:'unavailable',offlineDetails:'Example only.',localCapabilities:[],remoteCapabilities:['report'],dataEgress:['summary']};m.permissions.networkOrigins=['https://provider.example.invalid'];await upload(JSON.stringify(m));await execute();const r=await download('#export-results','cloud-metadata.json');assert.equal(r.valid,true);assert.equal(r.compatibility.compatible,false);assert.equal(r.model,null);assert.equal(r.summary.declaredExecution,'cloud');});
 await check('unconfigured cloud cards are not advertised as available execution',async()=>{assert.match(await page.locator('[data-package="digital.analyst"] .state').textContent(),/configuration/i);assert.equal(await page.locator('#compare').isVisible(),false);assert.match(await page.locator('#results-title').textContent(),/Inspection/);});
 await check('unconfigured cloud cards cannot export invented complete manifests',async()=>{await page.locator('[data-package="digital.analyst"]').click();assert.equal(await page.locator('#export-manifest').isDisabled(),true);assert.equal(await page.locator('#run-digital').isDisabled(),true);});
 await check('audit layout and ordinary host controls remain usable after imports',async()=>{await page.locator('[data-package="digital.audit"]').click();await upload(JSON.stringify(manifestFor('drone.agile')));await execute();await page.screenshot({path:out+'/audit-desktop.png',fullPage:true});for(const width of [390,320]){await page.setViewportSize({width,height:950});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}await page.screenshot({path:out+'/audit-mobile.png',fullPage:true});await page.locator('[data-host="humanoid"]').click();await idle();await page.locator('#step').click();await idle();assert.equal(await page.locator('#tick').textContent(),'1');});
 await check('long native file names do not overflow a narrow inspector',async()=>{await page.locator('[data-host="digital"]').click();await page.locator('[data-package="digital.audit"]').click();await page.setViewportSize({width:320,height:950});await page.locator('#inspection-file').setInputFiles({name:'x'.repeat(180)+'.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(manifestFor('drone.cinema')))});await idle();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);});
 await check('the full import/export workflow performs no external request or script execution',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(external,[]);});
}finally{await writeFile(out+'/results.json',JSON.stringify({browser:browser.version(),passed,errors,external},null,2));await browser.close();await server.close();}
