import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {loadRapier} from '../experiments/rover3d/engine.mjs';
import {createDroneSession} from '../packages/lab/drone-session.mjs';
import {createHumanoidSession} from '../packages/lab/humanoid-session.mjs';
import {inspectStoneData,MAX_EVIDENCE_BYTES} from '../packages/lab/inspection.mjs';
import {manifestFor} from '../packages/contract/reference.mjs';
import {getPackage} from '../packages/lab/registry.mjs';
import {digitalBenchmark} from '../packages/lab/benchmark.mjs';
const R=await loadRapier();
const source=id=>JSON.stringify(manifestFor(id),null,2);
const record=(create)=>{const s=create(R);try{s.advance(24);s.stop();return s.export();}finally{s.dispose();}};
test('AUDIT is a real local digital tool, not another fixed benchmark name',()=>{const p=getPackage('digital.audit');assert.equal(p.profile,'stone.digital.evidence/0.1');assert.deepEqual(p.tools,['validate-manifest','replay-reviewed-session']);assert.equal(p.model.kind,'none');});
test('AUDIT cannot accidentally fall through to fixed benchmark execution',async()=>{await assert.rejects(digitalBenchmark(R,'digital.audit','drone','hover'));});
test('manifest inspection needs no physics allocation and records actual byte integrity',async()=>{const text=source('drone.cinema');const r=await inspectStoneData(null,text,'drone');assert.equal(r.kind,'manifest');assert.equal(r.valid,true);assert.equal(r.compatibility.compatible,true);assert.equal(r.source.sha256,createHash('sha256').update(text).digest('hex'));assert.equal(r.source.bytes,Buffer.byteLength(text));assert.equal(r.verification,'metadata-only');assert.equal(r.authenticity,'not-verified');assert.equal(r.installation,'not-performed');});
test('validity is separate from cross-host compatibility',async()=>{const r=await inspectStoneData(null,source('drone.cinema'),'humanoid');assert.equal(r.valid,true);assert.equal(r.compatibility.compatible,false);});
test('auto selects a trusted offline profile, never permissions supplied by the file',async()=>{const m=manifestFor('humanoid.fluid');const r=await inspectStoneData(null,JSON.stringify(m),'auto');assert.equal(r.compatibility.compatible,true);assert.equal(r.model,null);});
test('unknown target host rejects',async()=>{await assert.rejects(inspectStoneData(null,source('drone.cinema'),'__proto__'));});
test('invalid manifest yields bounded errors without echoing raw input',async()=>{const m=JSON.parse(source('drone.cinema'));m.secret='DO_NOT_ECHO';const r=await inspectStoneData(null,JSON.stringify(m),'auto');assert.equal(r.valid,false);assert.equal(JSON.stringify(r).includes('DO_NOT_ECHO'),false);assert.equal(r.compatibility,null);});
test('canonical manifest size limit is preserved within the larger recording limit',async()=>{const text=source('drone.cinema')+' '.repeat(65537);const r=await inspectStoneData(null,text,'auto');assert.equal(r.valid,false);assert.equal(r.errors[0].code,'size');});
for(const [name,text] of [['not-text',null],['empty',''],['source-code','globalThis.attacked=true'],['array','[]'],['unknown-format','{"format":"other"}'],['ASCII oversize',' '.repeat(MAX_EVIDENCE_BYTES+1)],['UTF8 oversize','é'.repeat(MAX_EVIDENCE_BYTES)]])test('rejects '+name,async()=>{await assert.rejects(inspectStoneData(R,text,'auto'));assert.equal(globalThis.attacked,undefined);});
for(const [host,create] of [['drone',createDroneSession],['humanoid',createHumanoidSession]])test('actual '+host+' command recording is reexecuted with Stop preserved',async()=>{const d=record(create),text=JSON.stringify(d,null,2);const r=await inspectStoneData(R,text,host);assert.equal(r.kind,'recording');assert.equal(r.valid,true);assert.equal(r.verification,'engine-reexecution');assert.equal(r.summary.steps,24);assert.equal(r.summary.status,'stopped');assert.equal(r.summary.engineVersion,'0.20.0');assert.equal(r.authenticity,'not-verified');assert.equal(r.model,null);});
test('forged successful terminal status cannot be validated',async()=>{const d=structuredClone(record(createDroneSession));d.finalStatus='succeeded';await assert.rejects(inspectStoneData(R,JSON.stringify(d),'drone'));});
test('recording host mismatch cannot allocate another host',async()=>{const d=record(createDroneSession);await assert.rejects(inspectStoneData(null,JSON.stringify(d),'humanoid'));});
test('inspection does not mutate an existing live session',async()=>{const s=createDroneSession(R);try{s.advance(2);const before=s.read();await inspectStoneData(R,JSON.stringify(record(createHumanoidSession)),'auto');assert.deepEqual(s.read(),before);}finally{s.dispose();}});
test('input recording with injected fields is rejected',async()=>{const d=structuredClone(record(createDroneSession));d.module='https://untrusted.invalid/code.mjs';await assert.rejects(inspectStoneData(R,JSON.stringify(d),'drone'));});
test('a future session format is not downgraded',async()=>{const d=structuredClone(record(createDroneSession));d.format='stone.drone.session/0.3';await assert.rejects(inspectStoneData(R,JSON.stringify(d),'auto'));});
