import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {readFileSync} from 'node:fs';
import {readStonePackage,MAX_PACKAGE_BYTES} from '../packages/contract/stone-package.mjs';import {createModelPackage,readModelPackage,inspectModelPackage} from '../packages/learned-rover/package-data.mjs';import {MODEL_SHA256} from '../packages/learned-rover/identity.mjs';import {learnedManifest} from '../packages/learned-rover/manifest.mjs';
const model=readFileSync(new URL('../experiments/learned-flow/model/model.json',import.meta.url),'utf8'),hash=x=>createHash('sha256').update(x).digest('hex');
const fixture=()=>({format:'stone.package/0.1',manifest:structuredClone(learnedManifest),runtime:{adapter:'stone.rover.cart/0.1',harnessVersion:'stone.flow-imitation.harness/0.1.0',artifactId:'policy'},artifacts:[{id:'policy',mediaType:'application/json',bytes:Buffer.byteLength(model),sha256:hash(model),text:model}]});
test('reference package round trip retains actual model bytes, exact artifact hashes and core manifest',async()=>{const made=await createModelPackage(model),text=JSON.stringify(made),r=await readStonePackage(text);assert.equal(r.package.artifacts[0].text,model);assert.equal(r.source.sha256,hash(text));assert.equal(r.package.manifest.id,'rover.flow-learned');assert.equal(r.artifacts[0].sha256,MODEL_SHA256);assert.ok(Object.isFrozen(r.package));});
test('package inspection separates integrity, admission, non-installation and publisher authenticity',async()=>{const r=await inspectModelPackage(JSON.stringify(fixture()),'rover');assert.equal(r.valid,true);assert.equal(r.compatibility.compatible,true);assert.equal(r.installation,'not-performed');assert.equal(r.authenticity,'not-verified');assert.equal(r.model,null);assert.equal(r.verification,'package-artifact-integrity');assert.equal(r.summary.artifactSha256,MODEL_SHA256);});
test('a valid package may be incompatible with the selected host',async()=>{const r=await inspectModelPackage(JSON.stringify(fixture()),'drone');assert.equal(r.valid,true);assert.equal(r.compatibility.compatible,false);});
for(const [name,edit] of [['wrong format',p=>p.format='other'],['root script',p=>p.script='execute()'],['runtime URL',p=>p.runtime.url='https://invalid/'],['bad manifest',p=>p.manifest={}],['missing asset',p=>p.artifacts=[]],['duplicate asset',p=>p.artifacts.push(p.artifacts[0])],['bad hash',p=>p.artifacts[0].sha256='0'.repeat(64)],['wrong byte count',p=>p.artifacts[0].bytes++],['asset URL',p=>p.artifacts[0].url='https://invalid/'],['wrong media',p=>p.artifacts[0].mediaType='text/javascript'],['oversized asset',p=>{p.artifacts[0].text=' '.repeat(65537);p.artifacts[0].bytes=65537;p.artifacts[0].sha256=hash(p.artifacts[0].text);}],['unbound asset',p=>p.runtime.artifactId='absent']])test('package parser rejects '+name,async()=>{const p=fixture();edit(p);await assert.rejects(readStonePackage(JSON.stringify(p)));});
for(const [name,edit] of [['unknown adapter',p=>p.runtime.adapter='stone.other/0.1'],['changed harness',p=>p.runtime.harnessVersion='stone.other/0.1'],['new valid model bytes',p=>{const a=p.artifacts[0];a.text+=' ';a.bytes++;a.sha256=hash(a.text);p.manifest.implementation.modelRef='stone.flow-imitation@sha256:'+a.sha256;}],['different permission request',p=>p.manifest.permissions.storage='none'],['different resource declaration',p=>p.manifest.resources.memoryMiB=1]])test('format validity does not admit '+name+' for execution',async()=>{const p=fixture();edit(p);const parsed=await readStonePackage(JSON.stringify(p));assert.ok(parsed.package);const r=await readModelPackage(JSON.stringify(p));assert.equal(r.compatibility.compatible,false);});
test('size and malformed JSON are rejected before package admission',async()=>{for(const text of [null,'{}','x',' '.repeat(MAX_PACKAGE_BYTES+1)])await assert.rejects(readStonePackage(text));});
test('Unicode display metadata does not change the model or become executable markup',async()=>{const p=fixture();p.manifest.name='Zażółć <b>FLOW</b>';const r=await inspectModelPackage(JSON.stringify(p),'auto');assert.equal(r.summary.declaredName,p.manifest.name);assert.equal(r.authenticity,'not-verified');assert.equal(r.compatibility.compatible,true);});

test('metadata object-key order does not change admission, unlike pinned artifact bytes',async()=>{const sort=v=>Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,sort(x)])):v;const p=sort(fixture());const r=await readModelPackage(JSON.stringify(p));assert.equal(r.compatibility.compatible,true);});

test('first textual hash replacement changes model metadata, not artifact integrity',async()=>{
 const raw=JSON.stringify(fixture()),changed=raw.replace(MODEL_SHA256,'0'.repeat(64));
 const r=await readModelPackage(changed);assert.equal(r.package.artifacts[0].sha256,MODEL_SHA256);assert.equal(r.knownArtifact,true);assert.equal(r.compatibility.compatible,false);
});
test('actual digest corruption and changed artifact bytes fail integrity, unlike an unknown consistent model',async()=>{
 for(const edit of [p=>p.artifacts[0].sha256='0'.repeat(64),p=>p.artifacts[0].text=p.artifacts[0].text.replace('0','1')]){const p=fixture();edit(p);await assert.rejects(readStonePackage(JSON.stringify(p)),/checksum/);}
 const p=fixture(),a=p.artifacts[0];a.text+=' ';a.bytes++;a.sha256=hash(a.text);const r=await inspectModelPackage(JSON.stringify(p));assert.equal(r.valid,true);assert.equal(r.summary.knownArtifact,false);assert.equal(r.compatibility.compatible,false);
});
test('package source receipts retain UTF-8 byte identity across inspection and admission',async()=>{
 const p=fixture();p.manifest.name='Żółw <img src=x>';const text=JSON.stringify(p,null,2)+'\n',r=await readModelPackage(text),audit=await inspectModelPackage(text);assert.equal(r.source.bytes,Buffer.byteLength(text));assert.equal(r.source.sha256,hash(text));assert.deepEqual(audit.source,r.source);
});
test('public sample is generated exclusively from the approved model and manifest',async()=>{
 const sample=readFileSync(new URL('../examples/FLOW-Learned.stone.json',import.meta.url),'utf8'),expected=JSON.stringify(await createModelPackage(model),null,2)+'\n';assert.equal(sample,expected);assert.equal((await readModelPackage(sample)).compatibility.compatible,true);
});
test('data-only AUDIT exposes declared evidence and operating requirements as unauthenticated data',async()=>{
 const r=await inspectModelPackage(JSON.stringify(fixture()));assert.deepEqual(r.summary.declaredEvidence,learnedManifest.evidence);assert.equal(r.summary.declaredLicense,'UNLICENSED');assert.deepEqual(r.summary.requirements.runtime,fixture().runtime);assert.deepEqual(r.summary.requirements.permissions,learnedManifest.permissions);assert.deepEqual(r.summary.requirements.resources,learnedManifest.resources);assert.equal(r.authenticity,'not-verified');assert.equal(r.model,null);
});
