import {freeze} from './common.mjs';
const profiles={rover:'stone.rover.control/0.1',drone:'stone.drone.rotors/0.1',humanoid:'stone.humanoid.reach/0.1',digital:'stone.digital.benchmark/0.1'};
const entry=(host,id,name,description,execution='local')=>({schema:'stone.lab.passport/0.1',id:host+'.'+id,host,name,description,version:'0.1.0',profile:profiles[host],form:'digital',execution,availability:host==='drone'?'planned':execution==='local'?'available':'configuration-required',implementation:host==='drone'?'planned':execution==='local'?'rule-based':'provider-model-with-harness',model:{kind:execution==='local'?'none':'server-configured'},harness:host==='digital'?'Run a fixed reference benchmark; return measured results and a bounded summary.':'Validate observations; decide bounded actions; retain host authority.',tools:host==='digital'?['simulate-reference-task','compare-completion','format-report']:['observe-'+host,'command-'+host],offline:host==='drone'?'not-implemented':execution==='local'?'full-task':execution==='hybrid'?'local-comparison-only':'unavailable',limits:host==='drone'?'Planned profile only. Drone implementation is unavailable; do not execute.':host==='humanoid'?'Anchored torso and two-joint arm only; no walking, balance or grasping.':host==='rover'?'Two reference lanes; not general navigation.':'Read-only benchmark reference. Cloud adapters are fixture-tested; live provider validation is still required.'});
export const PACKAGES=freeze([
entry('rover','flow','FLOW / Rover','Measured acceleration and approach.'),entry('rover','dart','DART / Rover','Faster lane handling.'),entry('rover','anchor','ANCHOR / Rover','Low-speed lane handling.'),
entry('drone','cinema','CINEMA','Smooth waypoint transitions.'),entry('drone','survey','SURVEY','Steady waypoint inspection.'),entry('drone','agile','AGILE','Responsive waypoint handling.'),
entry('humanoid','fluid','FLUID','Gradual reaching movements.'),entry('humanoid','precise','PRECISE','Slow, deliberate reaching.'),entry('humanoid','brisk','BRISK','Quicker target transitions.'),
entry('digital','compare','BENCH','Run fixed rover or humanoid benchmarks as a local digital tool.'),entry('digital','brief','BRIEF','Produce an evidence-first local digest.'),entry('digital','analyst','ANALYST','Configured-provider report; no live provider is connected by default.','cloud'),entry('digital','hybrid','HYBRID','Local benchmark plus optional cloud report; explicit local-only fallback.','hybrid')
]);
export function getPackage(id){const p=PACKAGES.find(p=>p.id===id);if(!p)throw new TypeError('Unknown Stone package.');return p;}
export function compatible(id,host,execution){try{const p=getPackage(id);return p.host===host&&p.execution===execution;}catch{return false;}}
export const packagesFor=host=>PACKAGES.filter(p=>p.host===host);
