import {chromium} from 'playwright-core';import assert from 'node:assert/strict';import {startServer} from '../server.mjs';
const server=await startServer(0),browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,chromiumSandbox:true});let passed=0;
async function check(name,fn){const context=await browser.newContext();try{await fn(context);passed++;console.log('PASS',name);}finally{await context.close();}}
try{
 await check('a genuinely stalled worker can be terminated by Stop and recovered by Reset',async c=>{
 await c.route('**/worker.mjs',r=>r.fulfill({contentType:'text/javascript',body:'self.onmessage=()=>{while(true){}};'}));
 const p=await c.newPage();await p.goto(server.url);await p.waitForTimeout(250);await p.locator('#stop').click({timeout:2000});assert.equal(await p.locator('body').getAttribute('data-phase'),'stopped');
 await c.unroute('**/worker.mjs');await p.locator('#reset').click();await p.waitForFunction(()=>document.body.dataset.ready==='true'&&document.body.dataset.phase==='ready');
 });
 await check('a missing worker fails visibly without unresponsive controls',async c=>{await c.route('**/worker.mjs',r=>r.fulfill({status:404,body:'Missing'}));const p=await c.newPage();await p.goto(server.url);await p.waitForFunction(()=>document.body.dataset.phase==='error');assert.equal(await p.locator('#error').isVisible(),true);assert.equal(await p.locator('#reset').isEnabled(),true);});
 await check('malformed worker reply is rejected instead of advancing the machine',async c=>{await c.route('**/worker.mjs',r=>r.fulfill({contentType:'text/javascript',body:'self.onmessage=e=>self.postMessage({id:e.data.id,ok:false,error:"UNTRUSTED_SENTINEL"});'}));const p=await c.newPage();await p.goto(server.url);await p.waitForFunction(()=>document.body.dataset.phase==='error');assert.equal((await p.locator('body').innerText()).includes('UNTRUSTED_SENTINEL'),false);assert.equal(await p.locator('#tick').textContent(),'0');});
 await check('real WebGL context loss falls back to plan without changing engine time',async c=>{const p=await c.newPage();await p.goto(server.url);await p.waitForFunction(()=>document.body.dataset.ready==='true');await p.locator('#step').click();await p.waitForFunction(()=>document.body.dataset.busy==='false');const t=await p.locator('#tick').textContent();assert.equal(await p.evaluate(()=>{const g=document.querySelector('#viewport canvas').getContext('webgl2'),e=g.getExtension('WEBGL_lose_context');if(!e)return false;e.loseContext();return true;}),true);await p.waitForFunction(()=>!document.querySelector('#plan').hidden);assert.equal(await p.locator('#tick').textContent(),t);assert.equal(await p.locator('#viewplan').getAttribute('aria-pressed'),'true');await p.locator('#step').click();await p.waitForFunction(()=>document.body.dataset.busy==='false');assert.equal(Number(await p.locator('#tick').textContent()),Number(t)+1);});
 await check('an invalid worker command cannot replace the engine or import code',async c=>{const p=await c.newPage();await p.goto(server.url);await p.waitForFunction(()=>document.body.dataset.ready==='true');const result=await p.evaluate(()=>new Promise((resolve,reject)=>{const w=new Worker('/worker.mjs',{type:'module'});const timer=setTimeout(()=>{w.terminate();reject(new Error('timeout'));},8000);w.onmessage=e=>{clearTimeout(timer);w.terminate();resolve(e.data);};w.postMessage({id:1,type:'eval',payload:{url:'https://example.invalid'}});}));assert.equal(result.ok,false);});
 console.log('FAULT TESTS',passed);
}finally{await browser.close();await server.close();}
