import {chromium} from '../node_modules/playwright-core/index.mjs';
import {startServer} from '../server.mjs';import {readFile,mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
import {loadRapier} from '../../../experiments/rover3d/engine.mjs';
import {loadPolicy,MODEL_SHA256} from '../../../experiments/learned-flow/browser-runtime.mjs';
import {compareModelStones,replayModelRecording} from '../../../packages/learned-rover/session.mjs';
const R=await loadRapier(),model=await loadPolicy(await readFile(new URL('../../../experiments/learned-flow/model/model.json',import.meta.url),'utf8'));
const server=await startServer(0),browser=await chromium.launch({executablePath:process.env.CHROME_PATH??'/usr/bin/google-chrome',headless:true,chromiumSandbox:true});
const context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],external=[],requests=[],passed=[];
const out='evidence/live-model-local';await mkdir(out,{recursive:true});
context.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));
await context.route('**/*',r=>r.request().url().startsWith(server.url)?r.continue():(external.push(r.request().url()),r.abort()));
const idle=()=>page.waitForFunction(()=>document.body.dataset.busy==='false'),ready=()=>page.waitForFunction(()=>document.body.dataset.phase==='ready'&&document.body.dataset.busy==='false');
const ok=s=>{passed.push(s);console.log('PASS '+s);};
async function download(selector){const pending=page.waitForEvent('download');await page.locator(selector).click();const d=await pending;await d.saveAs(out+'/download.json');return JSON.parse(await readFile(out+'/download.json','utf8'));}
try{
 await page.goto(server.url);await ready();assert.equal(await page.locator('#decision-source').count(),1);assert.equal(await page.locator('#enable-model').isChecked(),false);assert.equal(await page.locator('[data-stone="rover.flow-learned"]').isVisible(),false);assert.ok(!requests.some(x=>x.includes('/models/')));ok('Default rules and route editor do not load a model silently');
 await page.locator('#enable-model').check();await ready();assert.equal(await page.locator('[data-stone="rover.flow-learned"]').isVisible(),true);assert.match(await page.textContent('#passport-implementation'),/Learned/);assert.match(await page.textContent('#passport-model'),/d9a1ef32/);const manifest=await download('#passport-export');assert.equal(manifest.implementation.kind,'learned-policy');assert.ok(manifest.implementation.modelRef.endsWith(MODEL_SHA256));ok('Opt-in loads and validates the saved model with an explicit model/harness passport');
 await page.locator('#start').click();await page.waitForFunction(()=>Number(document.querySelector('#tick').textContent)>90);await page.locator('#pause').click();await idle();const tick=await page.textContent('#tick');
 assert.ok(Number(await page.textContent('#inference-count'))>0);assert.match(await page.textContent('#decision-source'),/MODEL|GUARD/);await page.locator('[data-stone="rover.flow"]').click();await idle();assert.equal(await page.textContent('#tick'),tick);await page.locator('#step').click();await idle();await page.locator('[data-stone="rover.flow-learned"]').click();await idle();
 const after=Number(await page.textContent('#tick'));await page.locator('#stop').click();assert.equal(Number(await page.textContent('#tick')),after);
 const recording=await download('#export');assert.equal(recording.format,'stone.rover.policy-session/0.1');assert.equal(recording.finalStatus,'stopped');assert.equal(recording.finalStoneId,'rover.flow-learned');assert.ok(recording.counters.ruleDecisions>=1);assert.ok(recording.counters.modelCalls>0);
 const replay=replayModelRecording(R,JSON.stringify(recording),model);assert.equal(replay.policyVerified,true);assert.equal(replay.state.frame.observation.tick,after);ok('Live rule/model swaps retain state and Stop exports actual command/model attribution');
 await page.locator('#replay').click();await idle();assert.match(await page.textContent('#run-state'),/replay/i);assert.equal(await page.locator('#error').isVisible(),false);ok('Browser verifies both the identified policies and engine replay after worker termination');
 await page.locator('#live').click();await idle();await page.locator('#compare').click();await idle();let comparison=await download('#export-results');assert.equal(comparison.scope,'fixed-model-reference');assert.equal(comparison.modelSha256,MODEL_SHA256);assert.deepEqual(comparison.results,compareModelStones(R,'ramp-lane',model).results);ok('Four-way browser comparison matches Node including actual model-call counts');
 await page.selectOption('#course','flat-lane');await ready();await page.locator('#start').click();await page.waitForFunction(()=>document.body.dataset.phase==='complete',{timeout:20000});assert.equal(await page.locator('#error').isVisible(),false);assert.ok(Number(await page.textContent('#inference-count'))>400);ok('Saved model completes the visible flat-lane run without browser training');
 await page.locator('#compare').click();await idle();comparison=await download('#export-results');assert.deepEqual(comparison.results,compareModelStones(R,'flat-lane',model).results);ok('Second fixed course agrees exactly between browser and Node');
 await page.locator('#route-editor summary').click();assert.equal(await page.locator('[data-route="apply"]').isDisabled(),true);assert.match(await page.textContent('#model-scope'),/fixed/i);ok('Custom-route application is not silently treated as trained-model validation');
 await page.locator('#route-editor summary').click();await page.locator('#focus').click();await page.screenshot({path:out+'/learned-desktop.png',fullPage:true});
 for(const width of [390,320]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await page.screenshot({path:out+'/learned-mobile.png',fullPage:true});ok('The fourth Stone and execution indicators remain readable on narrow layouts');
 await page.setViewportSize({width:1440,height:1000});await page.locator('#enable-model').uncheck();await ready();assert.equal(await page.locator('[data-stone="rover.flow-learned"]').isVisible(),false);await page.locator('#route-editor summary').click();assert.equal(await page.locator('[data-route="apply"]').isDisabled(),false);await page.locator('[data-route="apply"]').click();await ready();assert.equal(await page.locator('#enable-model').isDisabled(),true);ok('Returning to rules preserves Route Studio and explicitly excludes custom routes from model mode');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);ok('All inference is local with no page errors, CDN or provider requests');
}finally{await writeFile(out+'/browser-results.json',JSON.stringify({passed,errors,external},null,2));await browser.close();await server.close();model.dispose();}
