import {chromium} from '../rover/node_modules/playwright-core/index.mjs';
import {startFieldServer} from '../field-lab/server.mjs';import {readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
import {readDataPackage} from '../../packages/data-quality/package.mjs';
const server=await startFieldServer(0);let browser,count=0;const ok=s=>console.log('PASS '+(++count)+' '+s);
try{
 browser=await chromium.launch({executablePath:process.env.CHROME_PATH??'/usr/bin/google-chrome',headless:true,chromiumSandbox:true});
 const context=await browser.newContext({acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(server.url+'#digital');await page.locator('#data-policy').waitFor();await page.waitForFunction(()=>!document.querySelector('#data-policy').disabled);
 const run=async()=>{await page.locator('#data-run').click();await page.waitForFunction(()=>!document.querySelector('#data-report-export').disabled);};
 const getDownload=async id=>{const event=page.waitForEvent('download');await page.locator(id).click();const d=await event;return await readFile(await d.path());};
 await page.locator('#data-file').setInputFiles({name:'inventory.csv',mimeType:'text/csv',buffer:Buffer.from('id,name\n001, Ada \n001, Ada ')});await page.waitForFunction(()=>!document.querySelector('#data-run').disabled);await run();
 const initial=JSON.parse(await getDownload('#data-report-export'));
 for(const [id,value] of [['rows',2],['columns',2],['missing',0],['duplicates',1],['whitespace',2],['findings',initial.findings.total]])assert.equal(await page.locator('#data-metric-'+id).innerText(),String(value));
 assert.equal(await page.locator('#data-preview td').nth(0).textContent(),'001');assert.equal(await page.locator('#data-preview td').nth(1).textContent(),' Ada ');assert.equal(await page.locator('#data-findings-table').isVisible(),true);assert.match(await page.locator('#data-findings-table').innerText(),/Edge whitespace.*Data row 1/s);ok('Visible metrics/findings match full report and original IDs/edge spaces are retained');
 await page.locator('#data-policy').selectOption('TIDY');await run();assert.match(await page.locator('#data-changes-table').innerText(),/" Ada ".*"Ada"/s);assert.equal(await page.locator('#data-result-details').getAttribute('open'),null);assert.match(await page.locator('#data-result-details').textContent(),/"trimmedCells": 2/);ok('Before/after preview agrees with changes and exact report starts collapsed');
 const before=await getDownload('#data-report-export');await page.getByText('Inspect, activate or export a portable Data Stone',{exact:true}).click();const activeBefore=await getDownload('#data-package-export');
 await page.locator('#data-author > summary').click();await page.locator('#data-author-name').fill('<img src=x onerror="window.injected=true">');await page.locator('#data-author-id').fill('digital.authored-inventory');await page.locator('#data-author-publisher').fill('Declared example');
 for(const check of ['missing','ragged','headers','duplicates','mixed','formula'])await page.locator('#data-author-check-'+check).uncheck();await page.locator('#data-author-trim').check();
 const workerRequests=[];page.on('request',r=>workerRequests.push(r.url()));await page.locator('#data-author-prepare').click();await page.waitForFunction(()=>!document.querySelector('#data-author-export').disabled);
 assert.deepEqual(await getDownload('#data-report-export'),before);assert.deepEqual(await getDownload('#data-package-export'),activeBefore);assert.ok(!workerRequests.some(x=>x.includes('/vendor/data-quality.mjs')));assert.equal(await page.evaluate(()=>window.injected),undefined);ok('Authoring only prepares/inspects; current report and active export remain unchanged');
 const draftBytes=await getDownload('#data-author-export'),draft=await readDataPackage(draftBytes.toString());assert.equal(draft.package.manifest.id,'digital.authored-inventory');assert.equal(draft.compatibility.compatible,true);assert.deepEqual(draft.config.checks,['whitespace']);const inspection=JSON.parse(await page.locator('#data-author-inspection').textContent());assert.equal(inspection.source.sha256,draft.source.sha256);
 await page.locator('#data-author-activate').click();assert.equal(await page.locator('#data-report-export').isDisabled(),true);await run();const authored=JSON.parse(await getDownload('#data-report-export'));assert.deepEqual(authored.checks,['whitespace']);assert.equal(authored.findings.total,2);assert.equal(authored.receipt.dataset.sha256,initial.receipt.dataset.sha256);assert.equal(authored.receipt.package.sha256,draft.source.sha256);ok('Explicit draft activation and Run use selected checks and retain original receipt');
 await page.locator('#data-package-file').setInputFiles({name:'authored.json',mimeType:'application/json',buffer:draftBytes});await page.waitForFunction(()=>!document.querySelector('#data-package-activate').disabled);assert.equal(await page.locator('#data-run').isDisabled(),true);await page.locator('#data-package-activate').click();assert.deepEqual(await getDownload('#data-package-export'),draftBytes);await run();assert.equal(JSON.parse(await getDownload('#data-report-export')).receipt.package.sha256,draft.source.sha256);ok('Authored third policy exports/reimports with exact package hash and runs through the shared adapter');
 await page.locator('#data-author-check-whitespace').uncheck();await page.locator('#data-author-prepare').click();await page.waitForFunction(()=>document.querySelector('#data-author-status').textContent.startsWith('Preparation failed'));assert.equal(await page.locator('#data-author-export').isDisabled(),true);assert.equal(await page.locator('#data-report-export').isDisabled(),false);await page.locator('#data-author-trim').uncheck();assert.equal(await page.locator('#data-author-omit').isDisabled(),true);assert.deepEqual(errors,[]);ok('Invalid check sets cannot create a draft and omit requires trim; dangerous name stays inert data');
 for(const width of [320,390]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('#data-metrics').isVisible(),true);}ok('Readable results and authoring fit 320/390px');
 await context.close();
 for(const mode of ['delayed','stalled'])for(const action of ['stop','leave','dispose']){
  const c=await browser.newContext(),p=await c.newPage();await p.addInitScript(()=>{const Native=Worker;window.dataWorkers=[];window.Worker=class extends Native{constructor(url,options){super(url,options);if(String(url).includes('/data-lab/worker.mjs')){window.dataWorkers.push(this);this.addEventListener('message',e=>{if(e.data?.started)this.started=true;});}}terminate(){this.wasTerminated=true;super.terminate();}};});
  const body=mode==='stalled'?'self.onmessage=()=>{self.postMessage({started:true});while(true){}};':`import {createDataPackage} from '/packages/data-quality/package.mjs';self.onmessage=async({data:m})=>{const result=Object.fromEntries(await Promise.all(['LENS','TIDY'].map(async name=>[name,JSON.stringify(await createDataPackage(name))])));self.postMessage({started:true});setTimeout(()=>self.postMessage({id:m.id,ok:true,result}),400);};`;
  await p.route('**/data-lab/worker.mjs',r=>r.fulfill({contentType:'text/javascript',body}));await p.goto(server.url+'#digital');await p.locator('#data-policy').waitFor();await p.waitForFunction(()=>window.dataWorkers.some(w=>w.started));
  if(action==='stop')await p.locator('#data-cancel').click();else if(action==='leave')await p.evaluate(()=>location.hash='#humanoid');else await p.evaluate(()=>window.dispatchEvent(new Event('pagehide')));
  await p.waitForFunction(()=>window.dataWorkers[0].wasTerminated);const status=await p.locator('#data-setup-status').textContent();await p.waitForTimeout(500);assert.equal(await p.locator('#data-setup-status').textContent(),status);assert.equal(await p.locator('#data-policy').isDisabled(),true);assert.equal(await p.locator('#data-package-export').isDisabled(),true);assert.equal(await p.evaluate(()=>window.dataWorkers.length),1);
  if(action!=='dispose'){await p.unroute('**/data-lab/worker.mjs');if(action==='leave'){await p.evaluate(()=>location.hash='#digital');await p.waitForFunction(()=>document.body.dataset.host==='digital');}assert.equal(await p.evaluate(()=>window.dataWorkers.length),1);await p.locator('#data-prepare-retry').click();await p.waitForFunction(()=>!document.querySelector('#data-policy').disabled);assert.equal(await p.locator('#data-package-export').isDisabled(),false);}
  ok(mode+' setup is terminated/invalidated on '+action+'; no late replacement or hidden restart'+(action==='dispose'?'':' and explicit retry recovers'));await c.close();
 }
 console.log('Data product browser cases passed: '+count);
}finally{await browser?.close();await server.close();}
